import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ClientWrapper} from "@/app/components/ClientWrapper.";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "motion automation",
  description: "Generated by create next app",
    icons: {
        icon: "/motion.png",
    },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <ClientWrapper>{children}</ClientWrapper>
    </body>
    </html>
  );
}
